services:
  postgres-workroomdb:
    image: postgres:16
    environment:
      POSTGRES_DB: workroomdb
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - workroomdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  workroom:
    image: workroom_image
    container_name: workroom_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-workroomdb
volumes:
  workroomdb-data: